language: go
go:
    - 1.8.x
    - 1.9.x
    - 1.10.x
install:
    - go get -v .
    - go get -v github.com/golang/lint/golint
script:
    - diff <(gofmt -d .) <(echo -n)
    - go vet ./...
    - golint -set_exit_status ./...
    - go test -race ./...
    - go build ./...
